In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv('play_tennis.csv')

In [3]:
data.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [4]:
data.drop(columns=['day'],inplace=True)

In [5]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [6]:
#solution:-

# P(Yes/sunny,hot,high,weak)=p(sunny/yes)*p(hot/yes)*p(high/yes)*p(weak/yes)*p(yes)
# P(no/sunny,hot,high,weak)=p(sunny/no)*p(hot/no)*p(high/no)*p(weak/no)*p(no)

In [7]:
#Training (Calulate all prob)

#Lookup Table(store prob)

#Testing

In [8]:
#P(yes)
#P(no)

In [9]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [10]:
py=9/14
pn=5/14
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [11]:
#Outlook

pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [12]:
POvercastNo=0
PRainNo=2/5
PSunnyNo=3/5

POvercastYes=4/9
PRainYes=3/9
PSunnyYes=2/9

In [13]:
#Temp

pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [14]:
PCoolNo=1/5
PHotNo=2/5
PMildNo=2/5

PCoolYes=3/9
PHotYes=2/9
PMildYes=4/9

In [15]:
#Humidity

pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [16]:
PHighNo=4/5
PNormalNo=1/5

PHighYes=3/9
PNormalYes=6/9

In [17]:
#Wind

pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [18]:
PStrongNo=3/5
PWeakNo=2/5

PStrongYes=3/9
PWeakYes=6/9

In [20]:
#Question:-
#Given-> Outlook=Sunny Temp=Hot Humidity=High Wind=Weak
#Play=?(y/n)

PYes=py*PSunnyYes*PHotYes*PHighYes*PWeakYes
PNo=pn*PSunnyNo*PHotNo*PHighNo*PWeakNo
print(PYes)
print(PNo)

0.007054673721340388
0.02742857142857143

In [ ]:
#Answer->(No Play)